import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="flex">
          <div className="min-h-screen w-[22%] bg-gray-700">sidebar</div>
          <div className="w-[78%] bg-red-300">
            <header className="h-[10vh] bg-green-500">header</header>
            <div>{children}</div>
          </div>
        </main>
      </body>
    </html>
  );
}
