import Sidebar from "@/components/sidebar";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="flex">
          <div className="min-h-screen w-[18%] bg-gray-700">
            <Sidebar />
          </div>
          <div className="w-[82%] bg-red-300">
            <header className="h-[9vh] bg-green-500">header</header>
            <div>{children}</div>
          </div>
        </main>
      </body>
    </html>
  );
}
